name: Action di Tag
on:
    push:
jobs:
    ciao:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Ciao, sono una stringa!"
            - run: echo "Hello, world!"
            - run: python --version
            - run: ifconfig
            - run: pip --version