name: Training modello ML
on:
    push:
jobs:
    training:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                sparse-checkout: |
                    tag

            - uses: actions/setup-python@v5
              with:
                python-version: '3.12.7'
            - run: |
                python -m pip install --upgrade pip
            - run: |
                python -r requirements.txt
              working-directory: tag
            - run: |
                python modello.py
              working-directory: tag

            - run: ls -la tag/